### ISSUE TITLE
Non-unique values

### ISSUE THREAD

**Issue by Suhansanu** [denismr/incremental-ks#1]
Regarding important note, IKS runs on the assumption that all the observations are unique. If it is not the case, the computed D statistic may not be exact (it can be higher than it should).

Is it possible to have a workaround for this issue? Does this restriction cause the treap data structure to become imbalanced and therefore log(n) improvement will be lost?

**Comment by denismr** [comment]
Please, be sure that you are using the most recent version of the algorithm (the one available in this repository right now), as the first implementation was bugged due to a problem related to this assumption.

Anyway, this limitation of the algorithm does not affect the time complexity at all. It still is log(n). It only affects the Kolmogorov Smirnov / Kuiper statistics. It does not change the Treap in any unexpected way.

Also, if only a small portion of your data is not unique, you can ignore this limitation (it's not like KS or Kuiper are perfect, anyways). However, if your data has several identical observations (like nominal values), you can soften the effects of the assumption by disturbing the values (adding small random values, for instance). However, if you are dealing with nominal values, I would not recommend using Kolmogorov Smirnov or Kuiper from the beginning.
